export { Log } from './log.interface';
export { Main } from './main.interface';
export { Matchers } from './matchers.interface';
export { Options } from './options.interface';
export { Result } from './result.interface';
export { Suites } from './suites.interface';
export { SpecSettings } from './spec-settings.interface';
export { Settings } from './settings.interface';
export { Testing } from './testing.interface';
